### ISSUE TITLE
Wrong sdk detected ?

### ISSUE THREAD

**Issue by pix106** [daktak/xposed_downloader#3]
Hi, 
I'm using v0.2 downloaded from fdroid, on a LP 5.0 tablet.
Arch is detected fine, got "arm", but sdk is not correctly detected, i get "sdk23".
As "sdk23" is the default value, maybe it was not detected at all.

If i understood the source, it uses build.prop values, right ?
So i did adb shell and : 
> shell@Tab2A7-10F:/ $ getprop |grep -i sdk                                      
> [ro.build.version.sdk]: [21]

Am i wrong ? If not, what can i do to help ?

Thanks

**Comment by breversa** [comment]
Same here with a Samsung Galaxy S II running CyanogenMod 12.1/Android 5.1.1.

SDK 23 is detected(?), while it should be SDK22.

**Comment by daktak** [comment]
Seems there was a bug, I've updated 0.2.1 please wipe data or re-install and check the Detected api / arch in logcat.

**Comment by pix106** [comment]
Using a built 0.2.1 source, i got this in logcat : 
>D/xposeddownloader_MainActivity(12156): Detected api: sdk21
>D/xposeddownloader_MainActivity(12156): Setting api: sdk23
>D/xposeddownloader_MainActivity(12156): Detected arch: arm
>D/xposeddownloader_MainActivity(12156): Setting arch: arm64

Using 0.2 from FDroid i got : 
>D/xposeddownloader_MainActivity(13291): Setting api: sdk23
>D/xposeddownloader_MainActivity(13291): Setting arch: arm

Detection seems fine, but not applied (did it on purpose ?).

Thanks !

**Comment by pix106** [comment]
Building with this test seems to be working better :) :
>if  (!Arrays.asList(**getResources().getStringArray(R.array.api)**).contains(newApi))

The same goes for arch test.

IMHO, these values should be detected everytime app starts, and app should alert and exit if detected values are not compatible.
Storing settings would be useless... :) Maybe you wanted to store it for faster start time ?
Not storing them would be more secure should app data be backuped then restored on an other device.
IMHO :)

**Comment by daktak** [comment]
0.2.2 updated in f-droid, you can re-select Auto if you want to re-detect. If you are restoring the app from titanium, you should not restore the data. Or use app/info to clear the data.
