### ISSUE TITLE
Download Xposed Installer too

### ISSUE THREAD

**Issue by breversa** [daktak/xposed_downloader#4]
What about the abitily to download the Xposed Installer from http://repo.xposed.info/module/de.robv.android.xposed.installer as well, since it's gonna be needed anyway ? :-)

**Comment by daktak** [comment]
Added download option in 0.2.1

**Comment by breversa** [comment]
Actually, it may be better to also download from here http://forum.xda-developers.com/showthread.php?t=3034811 (as it hosts the current latest 3.0_alpha4 version, while xposed.info only has 2.7_experimental1)

**Comment by daktak** [comment]
Yep, I'm pulling the 3.0 alpha

**Comment by breversa** [comment]
Typo in the menu : "DL Xposed Inst**f**aller APK"
