### ISSUE TITLE
External browser

### ISSUE THREAD

**Issue by EMK2000** [daktak/xposed_downloader#7]
When I choose to download from external browser, and open the app again, it just force closed. When i turn off external browser option, it can open again. Same problem in BaaketBuild downloader.  (BTW, will you consider to develop a similar OpenGapps downloader?)

**Comment by daktak** [comment]
Fixed in 0.2.3 and 0.2.4 respectively

**Comment by daktak** [comment]
Good idea regarding OpenGapps.
